name: object_detection_test
dependencies:
  - python=3.8
  - pip
  - pip:
    - pandas>=1.0.0
    - tqdm>=4.50.0
    - torch==1.6.0
    - pillow==8.2.0
    - torchvision
    - tensorboard==2.4.1
    - sacred==0.8.2
    - pymongo==3.11.3
    - opencv-python==4.5.1.48
    - pyyaml==5.4.1
    - seaborn==0.11.1
    - hydra_core

